title: ETCS Workshop
logo: /assets/img/kawaii.jpg
description: Photo taken by Yi Jiang at Sensoji, Tokyo.
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
